### ISSUE TITLE
Proyecto de RealidadAumentada

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/actividad-9-practica-de-proyecto-de-ra-equipo-magaly#1]
[PROYECTO DE REALIDAD AUMENTADA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-proyecto-de-ra-equipo-magaly/files/15267516/PROYECTO.DE.REALIDAD.AUMENTADA.pdf)

**Comment by EdwinOrtiz1412** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
